//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovayarabota.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sportsmen
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string Patronymic { get; set; }
        public string Phone { get; set; }
        public string Age { get; set; }
        public int HealthID { get; set; }
        public int PlanningID { get; set; }
        public int OptionsID { get; set; }
    
        public virtual Health Health { get; set; }
        public virtual Options Options { get; set; }
        public virtual Planning Planning { get; set; }
    }
}
